using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SobujEnterprise.Domain.Entities;
using SobujEnterprise.Infrastructure.Authentication;

namespace SobujEnterprise.Infrastructure.Persistence
{
    public static class DbInitializer
    {
        public static async Task InitializeAsync(AppDbContext context)
        {
            await context.Database.EnsureCreatedAsync();
            // EnsureCreated does not alter an existing local database. Keep this additive table
            // available for installations created before the account-address feature.
            // EnsureCreated builds a fresh Neon schema. This is an additive guard for
            // databases created before the customer-address feature.
            await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""UserAddresses"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone NULL,
    ""UserId"" integer NOT NULL REFERENCES ""Users"" (""Id"") ON DELETE CASCADE,
    ""Label"" character varying(80) NOT NULL,
    ""RecipientName"" character varying(150) NOT NULL,
    ""PhoneNumber"" character varying(50) NOT NULL,
    ""AddressLine"" character varying(500) NOT NULL,
    ""City"" character varying(100) NOT NULL,
    ""Area"" character varying(150) NULL,
    ""IsDefault"" boolean NOT NULL
);
CREATE INDEX IF NOT EXISTS ""IX_UserAddresses_UserId"" ON ""UserAddresses"" (""UserId"");");

            // 1. Seed Roles
            if (!await context.Roles.AnyAsync())
            {
                context.Roles.AddRange(
                    new Role { RoleName = "Admin" },
                    new Role { RoleName = "Customer" }
                );
                await context.SaveChangesAsync();
            }

            var adminRole = await context.Roles.FirstAsync(r => r.RoleName == "Admin");
            var customerRole = await context.Roles.FirstAsync(r => r.RoleName == "Customer");

            // 2. Seed Default Admin & Customer User
            if (!await context.Users.AnyAsync(u => u.Email == "admin@sobujenterprise.com"))
            {
                context.Users.Add(new User
                {
                    FullName = "Sobuj Enterprise Administrator",
                    Email = "admin@sobujenterprise.com",
                    PasswordHash = PasswordHasher.HashPassword("Admin@123"),
                    PhoneNumber = "01712204763",
                    RoleId = adminRole.Id
                });

                context.Users.Add(new User
                {
                    FullName = "Tanvir Ahmed",
                    Email = "customer@example.com",
                    PasswordHash = PasswordHasher.HashPassword("Customer@123"),
                    PhoneNumber = "01712345678",
                    RoleId = customerRole.Id
                });

                await context.SaveChangesAsync();
            }

            // 3. Seed Categories
            if (!await context.Categories.AnyAsync())
            {
                context.Categories.AddRange(
                    new Category { Name = "Office Supplies", Slug = "office-supplies", Description = "Essential desk, files, staplers & office accessories", Icon = "briefcase", ImageUrl = "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=600", IsFeatured = true, DisplayOrder = 1 },
                    new Category { Name = "Paper & Notebooks", Slug = "paper-notebooks", Description = "Premium A4 papers, spiral notebooks & journals", Icon = "book", ImageUrl = "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600", IsFeatured = true, DisplayOrder = 2 },
                    new Category { Name = "Writing & Correction", Slug = "writing-correction", Description = "Gel pens, ball pens, highlighters & correction tapes", Icon = "edit-3", ImageUrl = "https://images.unsplash.com/photo-1585336261026-418071839958?w=600", IsFeatured = true, DisplayOrder = 3 },
                    new Category { Name = "Art & Craft Supplies", Slug = "art-craft-supplies", Description = "Watercolors, sketchbooks, acrylics, brushes & clay", Icon = "palette", ImageUrl = "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600", IsFeatured = true, DisplayOrder = 4 },
                    new Category { Name = "School Essentials", Slug = "school-essentials", Description = "Geometry sets, pencil boxes, crayons & accessories", Icon = "smile", ImageUrl = "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600", IsFeatured = true, DisplayOrder = 5 },
                    new Category { Name = "Desk Organization", Slug = "desk-organization", Description = "Pen holders, document trays, organizers & sticky notes", Icon = "grid", ImageUrl = "https://images.unsplash.com/photo-1584727638096-042c45049ebe?w=600", IsFeatured = true, DisplayOrder = 6 }
                );
                await context.SaveChangesAsync();
            }

            // 4. Seed Brands
            if (!await context.Brands.AnyAsync())
            {
                context.Brands.AddRange(
                    new Brand { Name = "Double A", Slug = "double-a", LogoUrl = "https://seeklogo.com/images/D/double-a-paper-logo-8A1901C90D-seeklogo.com.png", Website = "https://doubleapaper.com", IsFeatured = true },
                    new Brand { Name = "Pilot", Slug = "pilot", LogoUrl = "https://cdn.worldvectorlogo.com/logos/pilot-pen.svg", Website = "https://pilotpen.com", IsFeatured = true },
                    new Brand { Name = "Deli", Slug = "deli", LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/e/e8/Deli_Company_Logo.svg", Website = "https://deliworld.com", IsFeatured = true },
                    new Brand { Name = "Faber-Castell", Slug = "faber-castell", LogoUrl = "https://cdn.worldvectorlogo.com/logos/faber-castell.svg", Website = "https://faber-castell.com", IsFeatured = true },
                    new Brand { Name = "Matador", Slug = "matador", LogoUrl = "", Website = "https://matador.com.bd", IsFeatured = true },
                    new Brand { Name = "Good Luck", Slug = "good-luck", LogoUrl = "", Website = "https://prangroup.com", IsFeatured = true },
                    new Brand { Name = "Fresh", Slug = "fresh", LogoUrl = "", Website = "https://mgi.org", IsFeatured = true },
                    new Brand { Name = "Doms", Slug = "doms", LogoUrl = "https://seeklogo.com/images/D/doms-logo-E9DCDB8FF4-seeklogo.com.png", Website = "https://domsindia.com", IsFeatured = true },
                    new Brand { Name = "Kangaro", Slug = "kangaro", LogoUrl = "", Website = "https://kangaro.com", IsFeatured = true },
                    new Brand { Name = "Zebra", Slug = "zebra", LogoUrl = "https://cdn.worldvectorlogo.com/logos/zebra-pen.svg", Website = "https://zebrapen.com", IsFeatured = true },
                    new Brand { Name = "Casio", Slug = "casio", LogoUrl = "", Website = "https://casio.com", IsFeatured = true },
                    new Brand { Name = "Uni-ball", Slug = "uni-ball", LogoUrl = "", Website = "https://uniball.com", IsFeatured = true }
                );
                await context.SaveChangesAsync();
            }

            // 5. Seed WhatsApp Message Templates
            if (!await context.WhatsAppTemplates.AnyAsync())
            {
                context.WhatsAppTemplates.AddRange(
                    new WhatsAppTemplate
                    {
                        TemplateType = "Standard_COD",
                        Title = "Standard Cash on Delivery Template",
                        MessageFormat = "👋 Hello Sobuj Enterprise!\nI have placed an order on your website.\n\n🛒 *Order ID:* {OrderId}\n👤 *Customer:* {CustomerName}\n📞 *Phone:* {CustomerPhone}\n📍 *Address:* {Address}, {City}\n💰 *Total Payable:* ৳{TotalAmount} (Cash on Delivery)\n\n📦 *Items Ordered:*\n{ItemsList}\n\n📝 *Note:* {Note}\n\nPlease confirm and dispatch my order. Thank you!",
                        IsDefault = true
                    },
                    new WhatsAppTemplate
                    {
                        TemplateType = "Express_Delivery",
                        Title = "Urgent / Express Office Delivery",
                        MessageFormat = "🚨 *URGENT ORDER* - Sobuj Enterprise!\nI urgently require these stationery supplies for office use.\n\n⚡ *Order ID:* {OrderId}\n👤 *Recipient:* {CustomerName}\n📞 *Phone:* {CustomerPhone}\n📍 *Delivery Location:* {Address}, {City}\n💵 *Amount:* ৳{TotalAmount}\n\n📋 *Urgent Items List:*\n{ItemsList}\n\nPlease let me know when your rider can deliver this today. Thanks!",
                        IsDefault = false
                    },
                    new WhatsAppTemplate
                    {
                        TemplateType = "Corporate_Bulk",
                        Title = "Corporate / Bulk Stationery Inquiry",
                        MessageFormat = "🏢 *CORPORATE REQUISITION* - Sobuj Enterprise\nGreetings! We have submitted a bulk order request.\n\n📑 *Requisition No:* {OrderId}\n👤 *Contact Person:* {CustomerName}\n📞 *Phone:* {CustomerPhone}\n🏢 *Delivery Address:* {Address}, {City}\n📊 *Quotation Estimate:* ৳{TotalAmount}\n\n📝 *Items Details:*\n{ItemsList}\n\nPlease confirm the delivery schedule for this consignment. Thank you!",
                        IsDefault = false
                    }
                );
                await context.SaveChangesAsync();
            }

            // 6. Seed Filter Attributes with Specific Category Links
            if (!await context.FilterAttributes.AnyAsync())
            {
                var paperCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "paper-notebooks");
                var writingCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "writing-correction");
                var officeCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "office-supplies");

                var paperSizeAttr = new FilterAttribute { Name = "Paper Size", Code = "paper_size", CategoryId = paperCat?.Id, DisplayType = "Checkbox", DisplayOrder = 1 };
                var gsmAttr = new FilterAttribute { Name = "Paper GSM", Code = "gsm", CategoryId = paperCat?.Id, DisplayType = "Checkbox", DisplayOrder = 2 };
                var tipSizeAttr = new FilterAttribute { Name = "Pen Nib Size", Code = "tip_size", CategoryId = writingCat?.Id, DisplayType = "Checkbox", DisplayOrder = 3 };
                var colorAttr = new FilterAttribute { Name = "Ink Color", Code = "color", CategoryId = writingCat?.Id, DisplayType = "ColorSwatch", DisplayOrder = 4 };

                context.FilterAttributes.AddRange(paperSizeAttr, gsmAttr, tipSizeAttr, colorAttr);
                await context.SaveChangesAsync();

                context.FilterAttributeValues.AddRange(
                    new FilterAttributeValue { FilterAttributeId = paperSizeAttr.Id, Value = "A4", DisplayOrder = 1 },
                    new FilterAttributeValue { FilterAttributeId = paperSizeAttr.Id, Value = "A5", DisplayOrder = 2 },
                    new FilterAttributeValue { FilterAttributeId = paperSizeAttr.Id, Value = "Legal", DisplayOrder = 3 },
                    new FilterAttributeValue { FilterAttributeId = gsmAttr.Id, Value = "70 GSM", DisplayOrder = 1 },
                    new FilterAttributeValue { FilterAttributeId = gsmAttr.Id, Value = "80 GSM", DisplayOrder = 2 },
                    new FilterAttributeValue { FilterAttributeId = gsmAttr.Id, Value = "100 GSM", DisplayOrder = 3 },
                    new FilterAttributeValue { FilterAttributeId = tipSizeAttr.Id, Value = "0.38mm", DisplayOrder = 1 },
                    new FilterAttributeValue { FilterAttributeId = tipSizeAttr.Id, Value = "0.5mm", DisplayOrder = 2 },
                    new FilterAttributeValue { FilterAttributeId = tipSizeAttr.Id, Value = "0.7mm", DisplayOrder = 3 },
                    new FilterAttributeValue { FilterAttributeId = colorAttr.Id, Value = "Black", ColorHex = "#111827", DisplayOrder = 1 },
                    new FilterAttributeValue { FilterAttributeId = colorAttr.Id, Value = "Blue", ColorHex = "#1D4ED8", DisplayOrder = 2 },
                    new FilterAttributeValue { FilterAttributeId = colorAttr.Id, Value = "Red", ColorHex = "#DC2626", DisplayOrder = 3 }
                );
                await context.SaveChangesAsync();
            }

            // 7. Seed Products
            if (!await context.Products.AnyAsync())
            {
                var doubleABrand = await context.Brands.FirstOrDefaultAsync(b => b.Slug == "double-a");
                var pilotBrand = await context.Brands.FirstOrDefaultAsync(b => b.Slug == "pilot");
                var deliBrand = await context.Brands.FirstOrDefaultAsync(b => b.Slug == "deli");
                var fcBrand = await context.Brands.FirstOrDefaultAsync(b => b.Slug == "faber-castell");
                var domsBrand = await context.Brands.FirstOrDefaultAsync(b => b.Slug == "doms");
                var zebraBrand = await context.Brands.FirstOrDefaultAsync(b => b.Slug == "zebra");

                var paperCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "paper-notebooks");
                var writingCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "writing-correction");
                var officeCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "office-supplies");
                var artCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "art-craft-supplies");
                var schoolCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "school-essentials");
                var orgCat = await context.Categories.FirstOrDefaultAsync(c => c.Slug == "desk-organization");

                context.Products.AddRange(
                    new Product
                    {
                        Title = "Double A Copier Paper A4 80 GSM (500 Sheets/Ream)",
                        Slug = "double-a-copier-paper-a4-80-gsm",
                        SKU = "PAP-DBL-A4-80",
                        ShortDescription = "High quality premium smooth copy paper suitable for laser, inkjet and photocopiers.",
                        Description = "Double A Paper is globally renowned for its high quality, smooth texture, bright white finish, and zero jamming reliability.",
                        Price = 560.00m,
                        DiscountPrice = 520.00m,
                        StockQuantity = 150,
                        CategoryId = paperCat?.Id ?? 2,
                        BrandId = doubleABrand?.Id,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop",
                        IsFeatured = true,
                        IsNewArrival = true,
                        IsBestSeller = true,
                        Rating = 4.9m,
                        ReviewCount = 84,
                        Tags = "paper,a4,double a,copier,office"
                    },
                    new Product
                    {
                        Title = "Pilot G2 Premium Gel Roller Pen 0.5mm (Pack of 3)",
                        Slug = "pilot-g2-gel-pen-0-5mm-pack-3",
                        SKU = "PEN-PLT-G2-05",
                        ShortDescription = "Smooth gel ink formula with comfortable rubber grip.",
                        Description = "Features super smooth writing gel ink, contoured rubber grip, and refillable design.",
                        Price = 450.00m,
                        DiscountPrice = 420.00m,
                        StockQuantity = 95,
                        CategoryId = writingCat?.Id ?? 3,
                        BrandId = pilotBrand?.Id,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1585336261026-418071839958?w=600&auto=format&fit=crop",
                        IsFeatured = true,
                        IsNewArrival = true,
                        IsBestSeller = true,
                        Rating = 5.0m,
                        ReviewCount = 120,
                        Tags = "pen,gel pen,pilot,writing"
                    },
                    new Product
                    {
                        Title = "Deli Heavy Duty Desktop Stapler with 1000 Staples",
                        Slug = "deli-heavy-duty-desktop-stapler",
                        SKU = "OFF-DELI-STP-01",
                        ShortDescription = "Sturdy steel mechanism stapler for 25-50 sheet capacity with ergonomic pressing handle.",
                        Description = "Deli Office classic desk stapler engineered for durability. Includes standard 24/6 staple pins starter pack.",
                        Price = 380.00m,
                        DiscountPrice = 340.00m,
                        StockQuantity = 60,
                        CategoryId = officeCat?.Id ?? 1,
                        BrandId = deliBrand?.Id,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop",
                        IsFeatured = true,
                        IsNewArrival = false,
                        IsBestSeller = true,
                        Rating = 4.8m,
                        ReviewCount = 42,
                        Tags = "stapler,office,deli,desk accessories"
                    },
                    new Product
                    {
                        Title = "Faber-Castell Connector Paint Box 24 Watercolor Set",
                        Slug = "faber-castell-connector-paint-box-24",
                        SKU = "ART-FC-WCL-24",
                        ShortDescription = "Vibrant watercolors with connector cups, mixing palette, and high pigment density.",
                        Description = "Connector paint set from Faber-Castell allows creative combinations of colors. Includes brush and paint cups.",
                        Price = 950.00m,
                        DiscountPrice = 880.00m,
                        StockQuantity = 40,
                        CategoryId = artCat?.Id ?? 4,
                        BrandId = fcBrand?.Id,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop",
                        IsFeatured = true,
                        IsNewArrival = true,
                        IsBestSeller = false,
                        Rating = 4.9m,
                        ReviewCount = 36,
                        Tags = "art,paint,watercolor,faber-castell"
                    },
                    new Product
                    {
                        Title = "Doms Neon Eraser & Pencil Combo Stationery Kit",
                        Slug = "doms-neon-stationery-combo-kit",
                        SKU = "SCH-DOMS-KIT-01",
                        ShortDescription = "Complete school combo with pencils, neon erasers, sharpener and ruler.",
                        Description = "High quality DOMS school kit perfect for students with super dark graphite pencils and dust-free soft erasers.",
                        Price = 180.00m,
                        DiscountPrice = 150.00m,
                        StockQuantity = 200,
                        CategoryId = schoolCat?.Id ?? 5,
                        BrandId = domsBrand?.Id,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1568832359672-e36cf5d74f54?w=600&auto=format&fit=crop",
                        IsFeatured = false,
                        IsNewArrival = true,
                        IsBestSeller = true,
                        Rating = 4.7m,
                        ReviewCount = 59,
                        Tags = "school,pencil,doms,eraser,kids"
                    },
                    new Product
                    {
                        Title = "Zebra Sarasa Clip Gel Pen 0.5mm Vintage Colors",
                        Slug = "zebra-sarasa-clip-gel-pen-vintage",
                        SKU = "PEN-ZEB-SRS-05",
                        ShortDescription = "Rapid dry water-based pigment gel pen with comfortable grip and sturdy binder clip.",
                        Description = "Zebra Sarasa Vintage series offers elegant sepia, navy, and dark green shades with quick dry smudge-free technology.",
                        Price = 190.00m,
                        DiscountPrice = 175.00m,
                        StockQuantity = 110,
                        CategoryId = writingCat?.Id ?? 3,
                        BrandId = zebraBrand?.Id,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop",
                        IsFeatured = true,
                        IsNewArrival = true,
                        IsBestSeller = true,
                        Rating = 4.9m,
                        ReviewCount = 78,
                        Tags = "zebra,pen,sarasa,gel,vintage"
                    },
                    new Product
                    {
                        Title = "Executive PU Leather Document Tray & Desk Organizer",
                        Slug = "executive-leather-desk-organizer",
                        SKU = "ORG-DSK-LTR-01",
                        ShortDescription = "Multi-slot luxury desk organizer for files, pens, smartphones, and note slips.",
                        Description = "Keep your executive workstation spotless with this handcrafted PU leather organizer.",
                        Price = 1250.00m,
                        DiscountPrice = 1150.00m,
                        StockQuantity = 25,
                        CategoryId = orgCat?.Id ?? 6,
                        BrandId = deliBrand?.Id,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop",
                        IsFeatured = true,
                        IsNewArrival = false,
                        IsBestSeller = false,
                        Rating = 4.8m,
                        ReviewCount = 19,
                        Tags = "desk,organizer,leather,office,storage"
                    },
                    new Product
                    {
                        Title = "Hardcover Spiral Dot Grid Journal A5 (160 Pages 100 GSM)",
                        Slug = "hardcover-spiral-dot-grid-journal-a5",
                        SKU = "NBK-JRN-A5-DOT",
                        ShortDescription = "Fountain pen friendly thick 100 GSM acid-free dot grid pages with elastic closure band.",
                        Description = "Designed for bullet journaling, sketching, and meeting notes without bleed-through or ghosting.",
                        Price = 420.00m,
                        DiscountPrice = 380.00m,
                        StockQuantity = 75,
                        CategoryId = paperCat?.Id ?? 2,
                        PrimaryImageUrl = "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&auto=format&fit=crop",
                        IsFeatured = true,
                        IsNewArrival = true,
                        IsBestSeller = true,
                        Rating = 5.0m,
                        ReviewCount = 92,
                        Tags = "notebook,journal,dot grid,a5,spiral"
                    }
                );
                await context.SaveChangesAsync();
            }
        }
    }
}
